Use sql_project_1;

-- Filtering & Sorting
-- Book Inventory: Retrieve all books that belong to the 'Classic' category.
SELECT * FROM books WHERE category = 'Classic';

-- Employee List: List the names and positions of all employees working in branch 'B001'.
SELECT emp_name, position FROM employees WHERE branch_id = 'B001';

-- Premium Rentals: Find all books that have a rental_price greater than $7.00.
SELECT * FROM books WHERE rental_price > 7.00;

-- Publisher Search: List the titles and authors of all books published by 'Penguin Books'.
SELECT Distinct book_title, author FROM books WHERE publisher = 'Penguin Books';

-- New Members: Show the first 5 members who registered, sorted by their reg_date.
SELECT * FROM members ORDER BY reg_date ASC LIMIT 5;

-- Category Analysis: Calculate the total number of books available in each category.
SELECT category, COUNT(*) as book_count FROM books GROUP BY category;

-- Branch Payroll: Find the total salary expenditure for each branch_id.
SELECT branch_id, SUM(salary) as total_salary FROM employees GROUP BY branch_id;

-- Active Loans: List all books that have been issued but have not yet been returned.
SELECT i.issued_book_name FROM issued_status i 
	LEFT JOIN return_status r ON i.issued_id = r.issued_id WHERE r.return_id IS NULL;

-- Frequent Borrowers: Identify members who have issued more than 2 books.
SELECT issued_member_id, COUNT(*) as issue_count 
	FROM issued_status GROUP BY issued_member_id HAVING COUNT(*) > 2;

-- Management Directory: Display the names of all managers along with their branch address and contact.
SELECT e.emp_name as manager_name, b.branch_address, b.contact_no 
	FROM branch b JOIN employees e ON b.manager_id = e.emp_id;

-- Author Productivity: Count how many unique book titles each author has.
SELECT author, COUNT(DISTINCT book_title) as unique_titles 
	FROM books GROUP BY author;

-- Salary Ranking: Rank employees within each branch based on their salary.
SELECT branch_id, emp_name, salary, 
       RANK() OVER (PARTITION BY branch_id ORDER BY salary DESC) as salary_rank FROM employees ;

-- High-Value Categories: Calculate average rental price per category (> $5.00).
SELECT category, AVG(rental_price) as avg_price 
	FROM books GROUP BY category HAVING AVG(rental_price) > 5.00;

-- Employee of the Month: Identify the employee who processed the most issuances.
SELECT issued_emp_id, COUNT(*) as issue_count 
	FROM issued_status GROUP BY issued_emp_id ORDER BY issue_count DESC LIMIT 1;

-- Member Activity Lifecycle: Find the first and last issuance date for each member.
SELECT issued_member_id, MIN(issued_date) as first_issuance, MAX(issued_date) as last_issuance 
	FROM issued_status GROUP BY issued_member_id;

-- Revenue by Genre: Total potential revenue generated by each category.
SELECT b.category, SUM(b.rental_price) as total_revenue FROM issued_status i 
	JOIN books b ON i.issued_book_isbn = b.isbn GROUP BY b.category;

-- Retention Analysis: Members registered in 2021 still active in 2024.
SELECT DISTINCT m.member_id, m.member_name 
	FROM members m JOIN issued_status i ON m.member_id = i.issued_member_id 
		WHERE year( m.reg_date) = '2021' AND year( i.issued_date) = '2024';

-- Inventory Turnover: Percentage of the total book collection currently issued out.
SELECT (COUNT(i.issued_id) * 100.0 / (SELECT COUNT(*) FROM books)) as turnover_percentage FROM issued_status i 
	LEFT JOIN return_status r ON i.issued_id = r.issued_id WHERE r.return_id IS NULL;


/*
Data Relationships Summary:
   To help you write your joins, here are the key connections:
      Employees & Branches: employees.branch_id = branch.branch_id
      Issuance & Members: issued_status.issued_member_id = members.member_id
      Issuance & Books: issued_status.issued_book_isbn = books.isbn
      Returns & Issuance: return_status.issued_id = issued_status.issued_id
      Management: branch.manager_id = employees.emp_id
*/